version: '3.3'

services:

  php:
    build:
      context: ./docker/php
      dockerfile: ./docker/php/DockerfileProd
    image: design-house:prod
    restart: always
    depends_on:
      - redis
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mysql-network
      - app-network

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - php
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

  queue:
    restart: always
    depends_on:
      - redis
    image: design-house:prod
    command: sh -c "php artisan queue:work > /dev/null 2>&1"
    volumes:
      - "./:/var/www/"
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mysql-network
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:

  redis-data:
    driver: local

networks:
  mysql-network:
    external: true
  app-network:
    driver: bridge
